// <auto-generated />
using API_MBProject.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API_MBProject.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250622190331_ConexaoSomee")]
    partial class ConexaoSomee
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("API_MBProject.Models.Usuario", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("bairro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cep")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cidadde")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("logradouro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("numero")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("senha")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("telefone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("uf")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("TB_USUARIOS", (string)null);

                    b.HasData(
                        new
                        {
                            id = 1,
                            bairro = "Bela Vista",
                            cep = "01310-100",
                            cidadde = "São Paulo",
                            email = "mariana.souza@eventosvip.com",
                            logradouro = "Av. Paulista",
                            nome = "Mariana Souza",
                            numero = "1000",
                            senha = "mari@2025",
                            telefone = "11980000001",
                            uf = "SP"
                        },
                        new
                        {
                            id = 2,
                            bairro = "Laranjeiras",
                            cep = "22240-003",
                            cidadde = "Rio de Janeiro",
                            email = "carlos.oliveira@fotografia.com",
                            logradouro = "Rua das Laranjeiras",
                            nome = "Carlos Oliveira",
                            numero = "200",
                            senha = "foto@2025",
                            telefone = "21980000002",
                            uf = "RJ"
                        },
                        new
                        {
                            id = 3,
                            bairro = "Centro",
                            cep = "30130-003",
                            cidadde = "Belo Horizonte",
                            email = "ana.lima@buffetfest.com",
                            logradouro = "Av. Afonso Pena",
                            nome = "Ana Beatriz Lima",
                            numero = "1500",
                            senha = "buffet@2025",
                            telefone = "31980000003",
                            uf = "MG"
                        },
                        new
                        {
                            id = 4,
                            bairro = "Centro Histórico",
                            cep = "90040-530",
                            cidadde = "Porto Alegre",
                            email = "lucas.martins@iluminacaoeventos.com",
                            logradouro = "Rua da Aurora",
                            nome = "Lucas Martins",
                            numero = "250",
                            senha = "luz@2025",
                            telefone = "51980000004",
                            uf = "RS"
                        },
                        new
                        {
                            id = 5,
                            bairro = "Pinheiros",
                            cep = "05402-000",
                            cidadde = "São Paulo",
                            email = "juliana.castro@decorvip.com",
                            logradouro = "Av. Rebouças",
                            nome = "Juliana Castro",
                            numero = "450",
                            senha = "decor@2025",
                            telefone = "11980000005",
                            uf = "SP"
                        },
                        new
                        {
                            id = 6,
                            bairro = "Centro",
                            cep = "80020-310",
                            cidadde = "Curitiba",
                            email = "fernando.lima@eventosmusicais.com",
                            logradouro = "Rua XV de Novembro",
                            nome = "Fernando Lima",
                            numero = "789",
                            senha = "musica@2025",
                            telefone = "41980000006",
                            uf = "PR"
                        },
                        new
                        {
                            id = 7,
                            bairro = "Setor Bueno",
                            cep = "74230-032",
                            cidadde = "Goiânia",
                            email = "patricia.nunes@eventoplanner.com",
                            logradouro = "Av. T-63",
                            nome = "Patrícia Nunes",
                            numero = "321",
                            senha = "planner@2025",
                            telefone = "62980000007",
                            uf = "GO"
                        },
                        new
                        {
                            id = 8,
                            bairro = "Itaigara",
                            cep = "41830-000",
                            cidadde = "Salvador",
                            email = "bruno.ferreira@eventsound.com",
                            logradouro = "Av. ACM",
                            nome = "Bruno Ferreira",
                            numero = "999",
                            senha = "sound@2025",
                            telefone = "71980000008",
                            uf = "BA"
                        },
                        new
                        {
                            id = 9,
                            bairro = "Aldeota",
                            cep = "60120-000",
                            cidadde = "Fortaleza",
                            email = "renata.dias@cerimonialeventos.com",
                            logradouro = "Rua Barão de Studart",
                            nome = "Renata Dias",
                            numero = "567",
                            senha = "cerimonial@2025",
                            telefone = "85980000009",
                            uf = "CE"
                        },
                        new
                        {
                            id = 10,
                            bairro = "Barra da Tijuca",
                            cep = "22640-102",
                            cidadde = "Rio de Janeiro",
                            email = "thiago.rocha@techfest.com",
                            logradouro = "Av. das Américas",
                            nome = "Thiago Rocha",
                            numero = "3500",
                            senha = "tech@2025",
                            telefone = "21980000010",
                            uf = "RJ"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
