// <auto-generated />
using System;
using API_MBProject.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API_MBProject.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250622014209_SegundaAtt")]
    partial class SegundaAtt
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("API_MBProject.Models.Usuario", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("biografia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("dtCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("endereco")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("links")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("senha")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("telefone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("tipoUsuario")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("TB_USUARIOS", (string)null);

                    b.HasData(
                        new
                        {
                            id = 1,
                            biografia = "Produtora de eventos corporativos e casamentos.",
                            dtCriacao = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            email = "mariana.souza@eventosvip.com",
                            endereco = "Av. Paulista, 1000 - São Paulo/SP",
                            links = "https://instagram.com/mari_eventos",
                            nome = "Mariana Souza",
                            senha = "mari@2025",
                            telefone = "11980000001",
                            tipoUsuario = 1
                        },
                        new
                        {
                            id = 2,
                            biografia = "Agente de talentos e responsável por contratações em festivais.",
                            dtCriacao = new DateTime(2024, 3, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            email = "carlosm@agenciashow.com",
                            endereco = "Rua das Rosas, 205 - Campinas/SP",
                            links = "https://linkedin.com/in/carlosmenezes",
                            nome = "Carlos Menezes",
                            senha = "carl@321",
                            telefone = "11980000002",
                            tipoUsuario = 1
                        },
                        new
                        {
                            id = 3,
                            biografia = "Organizadora de festas privadas e aniversários de luxo.",
                            dtCriacao = new DateTime(2024, 3, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            email = "fernanda.lima@festprime.com",
                            endereco = "Av. Atlântica, 750 - Rio de Janeiro/RJ",
                            links = "https://festprime.com/fernanda",
                            nome = "Fernanda Lima",
                            senha = "fernanda@fest",
                            telefone = "11980000003",
                            tipoUsuario = 1
                        },
                        new
                        {
                            id = 4,
                            biografia = "Responsável por agendamentos musicais em eventos públicos.",
                            dtCriacao = new DateTime(2024, 3, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            email = "jose.roberto@prefeituraevento.gov",
                            endereco = "Praça Central, 1 - Belo Horizonte/MG",
                            links = "",
                            nome = "José Roberto",
                            senha = "evento123",
                            telefone = "11980000004",
                            tipoUsuario = 1
                        },
                        new
                        {
                            id = 5,
                            biografia = "Contrata músicos para casas noturnas e bares temáticos.",
                            dtCriacao = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            email = "luciana.torres@noitesom.com",
                            endereco = "Rua Alegre, 99 - Porto Alegre/RS",
                            links = "https://noitesom.com/luciana",
                            nome = "Luciana Torres",
                            senha = "lucitorres2025",
                            telefone = "11980000005",
                            tipoUsuario = 1
                        },
                        new
                        {
                            id = 6,
                            biografia = "Dono da Casa dos Sons, especialista em shows de médio porte.",
                            dtCriacao = new DateTime(2024, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            email = "henrique.alves@casadossons.com",
                            endereco = "Rua do Som, 456 - Salvador/BA",
                            links = "https://casadossons.com",
                            nome = "Henrique Alves",
                            senha = "henri2025",
                            telefone = "11980000006",
                            tipoUsuario = 1
                        },
                        new
                        {
                            id = 7,
                            biografia = "Planejadora de eventos infantis e familiares com atrações musicais.",
                            dtCriacao = new DateTime(2024, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            email = "patricia@festou.com.br",
                            endereco = "Rua da Alegria, 78 - Recife/PE",
                            links = "https://festou.com.br",
                            nome = "Patrícia Rocha",
                            senha = "patfest2025",
                            telefone = "11980000007",
                            tipoUsuario = 1
                        },
                        new
                        {
                            id = 8,
                            biografia = "Produtor de festivais de rock e MPB.",
                            dtCriacao = new DateTime(2024, 4, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            email = "rafael.dias@produzshow.com",
                            endereco = "Rua Independência, 505 - Curitiba/PR",
                            links = "https://produzshow.com",
                            nome = "Rafael Dias",
                            senha = "dias@show",
                            telefone = "11980000008",
                            tipoUsuario = 1
                        },
                        new
                        {
                            id = 9,
                            biografia = "Curadora de artistas independentes para eventos regionais.",
                            dtCriacao = new DateTime(2024, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            email = "isabela.martins@musicsoul.com",
                            endereco = "Rua Harmonia, 300 - Florianópolis/SC",
                            links = "",
                            nome = "Isabela Martins",
                            senha = "isa123",
                            telefone = "11980000009",
                            tipoUsuario = 1
                        },
                        new
                        {
                            id = 10,
                            biografia = "Empresário do setor de entretenimento e shows.",
                            dtCriacao = new DateTime(2024, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            email = "thiago.nunes@vibeeventos.com",
                            endereco = "Av. das Luzes, 1122 - Goiânia/GO",
                            links = "https://vibeeventos.com",
                            nome = "Thiago Nunes",
                            senha = "nunes@2025",
                            telefone = "11980000010",
                            tipoUsuario = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
